name: Deploy Frontend

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Frontend Code
      uses: actions/checkout@v4
      
    - name: Setup SSH Connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy Frontend
      run: |
        echo "🚀 Starting frontend deployment..."
        echo "Repository: ${{ github.repository }}"
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"
        
        # Execute deployment with real-time logging
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          cd app/deployment/ && ./deploy.sh --frontend && docker system prune -af
        " 2>&1 | while IFS= read -r line; do
          echo "$(date '+%Y-%m-%d %H:%M:%S') | $line"
        done
        
    - name: Deployment Result
      if: always()
      run: |
        if [ $? -eq 0 ]; then
          echo "🎉 Frontend deployment completed successfully!"
        else
          echo "💥 Frontend deployment failed!"
          exit 1
        fi